US_STATES = [
    { 'iso': 'AL', 'title': 'Alabama' },
    { 'iso': 'AK', 'title': 'Alaska' },
    { 'iso': 'AZ', 'title': 'Arizona' },
    { 'iso': 'AR', 'title': 'Arkansas' },
    { 'iso': 'CA', 'title': 'California' },
    { 'iso': 'CO', 'title': 'Colorado' },
    { 'iso': 'CT', 'title': 'Connecticut' },
    { 'iso': 'DE', 'title': 'Delaware' },
    { 'iso': 'FL', 'title': 'Florida' },
    { 'iso': 'GA', 'title': 'Georgia' },
    { 'iso': 'HI', 'title': 'Hawaii' },
    { 'iso': 'ID', 'title': 'Idaho' },
    { 'iso': 'IL', 'title': 'Illinois' },
    { 'iso': 'IN', 'title': 'Indiana' },
    { 'iso': 'IA', 'title': 'Iowa' },
    { 'iso': 'KS', 'title': 'Kansas' },
    { 'iso': 'KY', 'title': 'Kentucky' },
    { 'iso': 'LA', 'title': 'Louisiana' },
    { 'iso': 'ME', 'title': 'Maine' },
    { 'iso': 'MD', 'title': 'Maryland' },
    { 'iso': 'MA', 'title': 'Massachusetts' },
    { 'iso': 'MI', 'title': 'Michigan' },
    { 'iso': 'MN', 'title': 'Minnesota' },
    { 'iso': 'MS', 'title': 'Mississippi' },
    { 'iso': 'MO', 'title': 'Missouri' },
    { 'iso': 'MT', 'title': 'Montana' },
    { 'iso': 'NE', 'title': 'Nebraska' },
    { 'iso': 'NV', 'title': 'Nevada' },
    { 'iso': 'NH', 'title': 'New Hampshire' },
    { 'iso': 'NJ', 'title': 'New Jersey' },
    { 'iso': 'NM', 'title': 'New Mexico' },
    { 'iso': 'NY', 'title': 'New York' },
    { 'iso': 'NC', 'title': 'North Carolina' },
    { 'iso': 'ND', 'title': 'North Dakota' },
    { 'iso': 'OH', 'title': 'Ohio' },
    { 'iso': 'OK', 'title': 'Oklahoma' },
    { 'iso': 'OR', 'title': 'Oregon' },
    { 'iso': 'PA', 'title': 'Pennsylvania' },
    { 'iso': 'RI', 'title': 'Rhode Island' },
    { 'iso': 'SC', 'title': 'South Carolina' },
    { 'iso': 'SD', 'title': 'South Dakota' },
    { 'iso': 'TN', 'title': 'Tennessee' },
    { 'iso': 'TX', 'title': 'Texas' },
    { 'iso': 'UT', 'title': 'Utah' },
    { 'iso': 'VT', 'title': 'Vermont' },
    { 'iso': 'VA', 'title': 'Virginia' },
    { 'iso': 'WA', 'title': 'Washington' },
    { 'iso': 'WV', 'title': 'West Virginia' },
    { 'iso': 'WI', 'title': 'Wisconsin' },
    { 'iso': 'WY', 'title': 'Wyoming' }
]
