from cubane.tests.templatetags.attribute_tags import *
from cubane.tests.templatetags.barcode_tags import *
from cubane.tests.templatetags.form_tags import *
from cubane.tests.templatetags.format_tags import *
from cubane.tests.templatetags.html_tags import *
from cubane.tests.templatetags.list_tags import *
from cubane.tests.templatetags.loop_tags import *
from cubane.tests.templatetags.message_tags import *
from cubane.tests.templatetags.resource_tags import *
from cubane.tests.templatetags.text_tags import *
from cubane.tests.templatetags.time_tags import *
from cubane.tests.templatetags.partition_tags import *