# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('iso', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO alpha-2')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Official name (CAPS)')),
                ('printable_name', models.CharField(db_index=True, max_length=128, verbose_name='Country name')),
                ('iso3', models.CharField(max_length=3, null=True, verbose_name='ISO alpha-3')),
                ('numcode', models.PositiveSmallIntegerField(null=True, verbose_name='ISO numeric')),
                ('landlocked', models.BooleanField(db_index=True, default=False)),
                ('flag_state', models.BooleanField(db_index=True, default=False)),
                ('calling_code', models.CharField(max_length=8, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
